# Generated by Django 2.1.1 on 2018-09-27 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='managers',
            field=models.ManyToManyField(related_name='art_managers', to=settings.AUTH_USER_MODEL),
        ),
    ]
