# Generated by Django 2.1.1 on 2018-09-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_art_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
