# Generated by Django 2.1.1 on 2018-09-27 19:28

import arts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_art_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=arts.models.download_file_location),
        ),
    ]
