# Generated by Django 2.1.1 on 2018-09-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0003_art_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
