# Generated by Django 2.1.1 on 2018-09-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0004_auto_20180925_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='slug',
            field=models.SlugField(default='slug-field'),
        ),
    ]
