# Generated by Django 2.1.1 on 2018-09-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0005_art_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
